os: linux
dist: focal
language: cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libocct-* occt-misc doxygen graphviz cmake libtbb-dev

compiler:
    - gcc
    - clang

cache:
    apt: true

branches:
    only:
        - devel

before_script:
    - cmake -S . -B build

script:
    - cmake --build build/ -j2
    - ctest -j2
