os: linux
dist: focal
language: cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libocct-* occt-misc doxygen graphviz libtbb-dev libxi-dev doxygen graphviz

compiler:
    - gcc
    - clang

cache:
    apt: true

branches:
    only:
        - master
        - devel

before_script:
    - cmake -S . -B build

# build and test
script:
    - cmake --build build/ -j2
    - cd build && ctest -VV -j2
