name: "Codespell"

on: pull_request
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: ./.git,./external,*.FCStd
          only_warn: 1
