# This workflow maintains the vcpkg cache of opencascade binaries (& dependencies)

name: "Cache OCCT build (Windows)"

on:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Cache OCCT
    runs-on: windows-latest
    steps:
      # parse baseline.json to find the version and portversion
      # this step is currently unused, but keep it for potential future use
      - name: Fetch OCCT Version
        id: occt_version
        run: |
          VCPKG_OCCT_METADATA=$VCPKG_INSTALLATION_ROOT/versions/baseline.json
          OCCT_VERSION=$(jq -r '.default["opencascade"]["baseline"]' $VCPKG_OCCT_METADATA)
          OCCT_PORT_VERSION=$(jq -r '.default["opencascade"]["port-version"]' $VCPKG_OCCT_METADATA)
          OCCT_NAME_VERSION=occt-${OCCT_VERSION}_${OCCT_PORT_VERSION}
          echo "::set-output name=occt_version_revision::$OCCT_NAME_VERSION"
          echo "OCCT VERSION: ${OCCT_NAME_VERSION}"

      - name: Hash VCPKG baseline
        id: vcpkg_hash
        run: |
          VCPKG_SHA=$(sha1sum -z $VCPKG_INSTALLATION_ROOT/versions/baseline.json | cut -d " " -f1)
          echo "vcpkg hash: ${VCPKG_SHA}"
          echo "::set-output name=vcpkg_hash::$VCPKG_SHA"

      - name: Restore OCCT cached build
        id: cache
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\vcpkg\archives\
          key: occt-build-${{ steps.vcpkg_hash.outputs.vcpkg_hash }}

      - name: Build/Install OCCT
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          vcpkg install opencascade[tbb]
        env:
          # force vcpkg to build x64
          VCPKG_DEFAULT_TRIPLET: x64-windows

